#!/bin/bash

set -e

echo "Welcome to MeshMVC installer!"

echo "Please enter install location"

# Prompt the user for a directory name
read -p "Enter directory name (default: current directory): " dirname

# Check if the dirname is not empty
if [[ -n "$dirname" ]]; then
    # Create the directory
    mkdir "$dirname" &> /dev/null

    # Change to the newly created directory
    cd "$dirname" &> /dev/null

    echo "Installing to: ($dirname) ..."
else
    echo "Installing to current directory..."
fi

echo "Verifying dependencies..."

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "jq is not installed. Installing jq..."
    
    # Check if the package manager is apt-get (Linux)
    if command -v apt-get &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y jq
    # Check if the package manager is yum (Linux)
    elif command -v yum &> /dev/null; then
        sudo yum update
        sudo yum install -y jq
    # Check if the package manager is dnf (Linux)
    elif command -v dnf &> /dev/null; then
        sudo dnf install -y jq
    # Check if the package manager is pacman (Linux)
    elif command -v pacman &> /dev/null; then
        sudo pacman -Sy jq --noconfirm
    # Check if Homebrew package manager is available (macOS)
    elif command -v brew &> /dev/null; then
        brew install jq
    else
        echo "Unable to install jq. Please install jq manually and re-run this script."
        exit 1
    fi
fi

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "Docker is not installed. Installing Docker..."
    
    # Check if the package manager is apt-get (Debian/Ubuntu)
    if command -v apt-get &> /dev/null; then
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        sudo systemctl enable docker
        sudo systemctl start docker
    # Check if the package manager is yum (RHEL/CentOS/Fedora)
    elif command -v yum &> /dev/null; then
        sudo yum install -y yum-utils
        sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        sudo yum install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl enable docker
        sudo systemctl start docker
    # Check if the package manager is dnf (Fedora)
    elif command -v dnf &> /dev/null; then
        sudo dnf install -y dnf-plugins-core
        sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
        sudo dnf install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl enable docker
        sudo systemctl start docker
    # Check if the package manager is pacman (Arch)
    elif command -v pacman &> /dev/null; then
        sudo pacman -Sy docker --noconfirm
        sudo systemctl enable docker
        sudo systemctl start docker
    # Check if the package manager is zypper (openSUSE)
    elif command -v zypper &> /dev/null; then
        sudo zypper install -y docker
        sudo systemctl enable docker
        sudo systemctl start docker
    # Check if Homebrew package manager is available (macOS)
    elif command -v brew &> /dev/null; then
        brew install docker
        brew services start docker        
    else
        echo "Unable to install Docker. Please install Docker manually and re-run this script."
        exit 1
    fi
fi

# Check if Docker Compose is installed
if ! command -v docker-compose &> /dev/null; then
    echo "Docker Compose is not installed. Installing Docker Compose..."

    # Check if the package manager is apt-get (Debian/Ubuntu)
    if command -v apt-get &> /dev/null; then
        sudo apt-get install -y docker-compose
    # Check if the package manager is yum (RHEL/CentOS/Fedora)
    elif command -v yum &> /dev/null || command -v dnf &> /dev/null; then
        sudo yum install -y docker-compose
    # Check if the package manager is pacman (Arch)
    elif command -v pacman &> /dev/null; then
        sudo pacman -Sy docker-compose --noconfirm
    # Check if the package manager is zypper (openSUSE)
    elif command -v zypper &> /dev/null; then
        sudo zypper install -y docker-compose
    # Check if Homebrew package manager is available (macOS)
    elif command -v brew &> /dev/null; then
        brew install docker-compose
    else
        echo "Unable to install Docker Compose. Please install Docker Compose manually."
        exit 1
    fi
fi

echo "Downloading MeshMVC..."

curl -sL $(curl -sL https://api.github.com/repos/MeshMVC/MeshMVC/tags | jq -r '.[0].tarball_url') -o MeshMVC-latest.tar

echo "Extracting MeshMVC..."
tar -xf MeshMVC-latest.tar --strip-components=1 &> /dev/null
rm MeshMVC-latest.tar

echo "Running server with docker..."
docker compose up -d

echo "Ready!"
echo "-> To stop the server, please run the command 'docker compose down'."
